package com.imory.product.dao;

import com.imory.product.dto.Product;
import com.imory.product.dto.ProductExample;
import com.imory.product.dto.ProductExample.Criteria;
import com.imory.product.dto.ProductExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class ProductSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    public String countByExample(ProductExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("product");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    public String deleteByExample(ProductExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("product");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    public String insertSelective(Product record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("product");
        
        if (record.getProduct_name() != null) {
            sql.VALUES("product_name", "#{product_name,jdbcType=VARCHAR}");
        }
        
        if (record.getMarque() != null) {
            sql.VALUES("marque", "#{marque,jdbcType=VARCHAR}");
        }
        
        if (record.getBarcode() != null) {
            sql.VALUES("barcode", "#{barcode,jdbcType=VARCHAR}");
        }
        
        if (record.getType_id() != null) {
            sql.VALUES("type_id", "#{type_id,jdbcType=INTEGER}");
        }
        
        if (record.getCategory_id() != null) {
            sql.VALUES("category_id", "#{category_id,jdbcType=INTEGER}");
        }
        
        if (record.getBrand_id() != null) {
            sql.VALUES("brand_id", "#{brand_id,jdbcType=INTEGER}");
        }
        
        if (record.getPrice() != null) {
            sql.VALUES("price", "#{price,jdbcType=DECIMAL}");
        }
        
        if (record.getMarket_price() != null) {
            sql.VALUES("market_price", "#{market_price,jdbcType=DECIMAL}");
        }
        
        if (record.getCost_price() != null) {
            sql.VALUES("cost_price", "#{cost_price,jdbcType=DECIMAL}");
        }
        
        if (record.getStock() != null) {
            sql.VALUES("stock", "#{stock,jdbcType=INTEGER}");
        }
        
        if (record.getWarning_stock() != null) {
            sql.VALUES("warning_stock", "#{warning_stock,jdbcType=INTEGER}");
        }
        
        if (record.getIntegral() != null) {
            sql.VALUES("integral", "#{integral,jdbcType=INTEGER}");
        }
        
        if (record.getPicture_url() != null) {
            sql.VALUES("picture_url", "#{picture_url,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=VARCHAR}");
        }
        
        if (record.getCreate_time() != null) {
            sql.VALUES("create_time", "#{create_time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIndex_type() != null) {
            sql.VALUES("index_type", "#{index_type,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    public String selectByExample(ProductExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("product_id");
        } else {
            sql.SELECT("product_id");
        }
        sql.SELECT("product_name");
        sql.SELECT("marque");
        sql.SELECT("barcode");
        sql.SELECT("type_id");
        sql.SELECT("category_id");
        sql.SELECT("brand_id");
        sql.SELECT("price");
        sql.SELECT("market_price");
        sql.SELECT("cost_price");
        sql.SELECT("stock");
        sql.SELECT("warning_stock");
        sql.SELECT("integral");
        sql.SELECT("picture_url");
        sql.SELECT("status");
        sql.SELECT("create_time");
        sql.SELECT("index_type");
        sql.FROM("product");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Product record = (Product) parameter.get("record");
        ProductExample example = (ProductExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("product");

        if (record.getProduct_id() != null) {
            sql.SET("product_id = #{record.product_id,jdbcType=INTEGER}");
        }

        if (record.getProduct_name() != null) {
            sql.SET("product_name = #{record.product_name,jdbcType=VARCHAR}");
        }

        if (record.getMarque() != null) {
            sql.SET("marque = #{record.marque,jdbcType=VARCHAR}");
        }

        if (record.getBarcode() != null) {
            sql.SET("barcode = #{record.barcode,jdbcType=VARCHAR}");
        }

        if (record.getType_id() != null) {
            sql.SET("type_id = #{record.type_id,jdbcType=INTEGER}");
        }

        if (record.getCategory_id() != null) {
            sql.SET("category_id = #{record.category_id,jdbcType=INTEGER}");
        }

        if (record.getBrand_id() != null) {
            sql.SET("brand_id = #{record.brand_id,jdbcType=INTEGER}");
        }

        if (record.getPrice() != null) {
            sql.SET("price = #{record.price,jdbcType=DECIMAL}");
        }

        if (record.getMarket_price() != null) {
            sql.SET("market_price = #{record.market_price,jdbcType=DECIMAL}");
        }

        if (record.getCost_price() != null) {
            sql.SET("cost_price = #{record.cost_price,jdbcType=DECIMAL}");
        }

        if (record.getStock() != null) {
            sql.SET("stock = #{record.stock,jdbcType=INTEGER}");
        }

        if (record.getWarning_stock() != null) {
            sql.SET("warning_stock = #{record.warning_stock,jdbcType=INTEGER}");
        }

        if (record.getIntegral() != null) {
            sql.SET("integral = #{record.integral,jdbcType=INTEGER}");
        }

        if (record.getPicture_url() != null) {
            sql.SET("picture_url = #{record.picture_url,jdbcType=VARCHAR}");
        }

        if (record.getStatus() != null) {
            sql.SET("status = #{record.status,jdbcType=VARCHAR}");
        }

        if (record.getCreate_time() != null) {
            sql.SET("create_time = #{record.create_time,jdbcType=TIMESTAMP}");
        }

        if (record.getIndex_type() != null) {
            sql.SET("index_type = #{record.index_type,jdbcType=INTEGER}");
        }

        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("product");
        
        sql.SET("product_id = #{record.product_id,jdbcType=INTEGER}");
        sql.SET("product_name = #{record.product_name,jdbcType=VARCHAR}");
        sql.SET("marque = #{record.marque,jdbcType=VARCHAR}");
        sql.SET("barcode = #{record.barcode,jdbcType=VARCHAR}");
        sql.SET("type_id = #{record.type_id,jdbcType=INTEGER}");
        sql.SET("category_id = #{record.category_id,jdbcType=INTEGER}");
        sql.SET("brand_id = #{record.brand_id,jdbcType=INTEGER}");
        sql.SET("price = #{record.price,jdbcType=DECIMAL}");
        sql.SET("market_price = #{record.market_price,jdbcType=DECIMAL}");
        sql.SET("cost_price = #{record.cost_price,jdbcType=DECIMAL}");
        sql.SET("stock = #{record.stock,jdbcType=INTEGER}");
        sql.SET("warning_stock = #{record.warning_stock,jdbcType=INTEGER}");
        sql.SET("integral = #{record.integral,jdbcType=INTEGER}");
        sql.SET("picture_url = #{record.picture_url,jdbcType=VARCHAR}");
        sql.SET("status = #{record.status,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.create_time,jdbcType=TIMESTAMP}");
        sql.SET("index_type = #{record.index_type,jdbcType=INTEGER}");
        
        ProductExample example = (ProductExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    public String updateByPrimaryKeySelective(Product record) {
        SQL sql = new SQL();
        sql.UPDATE("product");
        
        if (record.getProduct_name() != null) {
            sql.SET("product_name = #{product_name,jdbcType=VARCHAR}");
        }
        
        if (record.getMarque() != null) {
            sql.SET("marque = #{marque,jdbcType=VARCHAR}");
        }
        
        if (record.getBarcode() != null) {
            sql.SET("barcode = #{barcode,jdbcType=VARCHAR}");
        }
        
        if (record.getType_id() != null) {
            sql.SET("type_id = #{type_id,jdbcType=INTEGER}");
        }
        
        if (record.getCategory_id() != null) {
            sql.SET("category_id = #{category_id,jdbcType=INTEGER}");
        }
        
        if (record.getBrand_id() != null) {
            sql.SET("brand_id = #{brand_id,jdbcType=INTEGER}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("price = #{price,jdbcType=DECIMAL}");
        }
        
        if (record.getMarket_price() != null) {
            sql.SET("market_price = #{market_price,jdbcType=DECIMAL}");
        }
        
        if (record.getCost_price() != null) {
            sql.SET("cost_price = #{cost_price,jdbcType=DECIMAL}");
        }
        
        if (record.getStock() != null) {
            sql.SET("stock = #{stock,jdbcType=INTEGER}");
        }
        
        if (record.getWarning_stock() != null) {
            sql.SET("warning_stock = #{warning_stock,jdbcType=INTEGER}");
        }
        
        if (record.getIntegral() != null) {
            sql.SET("integral = #{integral,jdbcType=INTEGER}");
        }
        
        if (record.getPicture_url() != null) {
            sql.SET("picture_url = #{picture_url,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=VARCHAR}");
        }
        
        if (record.getCreate_time() != null) {
            sql.SET("create_time = #{create_time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIndex_type() != null) {
            sql.SET("index_type = #{index_type,jdbcType=INTEGER}");
        }
        
        sql.WHERE("product_id = #{product_id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    protected void applyWhere(SQL sql, ProductExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}