package com.imory.product.dao;

import com.imory.product.dto.Product;
import com.imory.product.dto.ProductExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    @SelectProvider(type=ProductSqlProvider.class, method="countByExample")
    int countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    @DeleteProvider(type=ProductSqlProvider.class, method="deleteByExample")
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    @Delete({
        "delete from product",
        "where product_id = #{product_id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer product_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    @Insert({
        "insert into product (product_name, marque, ",
        "barcode, type_id, ",
        "category_id, brand_id, ",
        "price, market_price, ",
        "cost_price, stock, ",
        "warning_stock, integral, ",
        "picture_url, status, ",
        "create_time, index_type)",
        "values (#{product_name,jdbcType=VARCHAR}, #{marque,jdbcType=VARCHAR}, ",
        "#{barcode,jdbcType=VARCHAR}, #{type_id,jdbcType=INTEGER}, ",
        "#{category_id,jdbcType=INTEGER}, #{brand_id,jdbcType=INTEGER}, ",
        "#{price,jdbcType=DECIMAL}, #{market_price,jdbcType=DECIMAL}, ",
        "#{cost_price,jdbcType=DECIMAL}, #{stock,jdbcType=INTEGER}, ",
        "#{warning_stock,jdbcType=INTEGER}, #{integral,jdbcType=INTEGER}, ",
        "#{picture_url,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{create_time,jdbcType=TIMESTAMP}, #{index_type,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="product_id", before=false, resultType=Integer.class)
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    @InsertProvider(type=ProductSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="product_id", before=false, resultType=Integer.class)
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    @SelectProvider(type=ProductSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="product_id", property="product_id", jdbcType= JdbcType.INTEGER, id=true),
        @Result(column="product_name", property="product_name", jdbcType= JdbcType.VARCHAR),
        @Result(column="marque", property="marque", jdbcType= JdbcType.VARCHAR),
        @Result(column="barcode", property="barcode", jdbcType= JdbcType.VARCHAR),
        @Result(column="type_id", property="type_id", jdbcType= JdbcType.INTEGER),
        @Result(column="category_id", property="category_id", jdbcType= JdbcType.INTEGER),
        @Result(column="brand_id", property="brand_id", jdbcType= JdbcType.INTEGER),
        @Result(column="price", property="price", jdbcType= JdbcType.DECIMAL),
        @Result(column="market_price", property="market_price", jdbcType= JdbcType.DECIMAL),
        @Result(column="cost_price", property="cost_price", jdbcType= JdbcType.DECIMAL),
        @Result(column="stock", property="stock", jdbcType= JdbcType.INTEGER),
        @Result(column="warning_stock", property="warning_stock", jdbcType= JdbcType.INTEGER),
        @Result(column="integral", property="integral", jdbcType= JdbcType.INTEGER),
        @Result(column="picture_url", property="picture_url", jdbcType= JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType= JdbcType.VARCHAR),
        @Result(column="create_time", property="create_time", jdbcType= JdbcType.TIMESTAMP),
        @Result(column="index_type", property="index_type", jdbcType= JdbcType.INTEGER)
    })
    List<com.imory.product.dto.Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    @Select({
        "select",
        "product_id, product_name, marque, barcode, type_id, category_id, brand_id, price, ",
        "market_price, cost_price, stock, warning_stock, integral, picture_url, status, ",
        "create_time, index_type",
        "from product",
        "where product_id = #{product_id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="product_id", property="product_id", jdbcType= JdbcType.INTEGER, id=true),
        @Result(column="product_name", property="product_name", jdbcType= JdbcType.VARCHAR),
        @Result(column="marque", property="marque", jdbcType= JdbcType.VARCHAR),
        @Result(column="barcode", property="barcode", jdbcType= JdbcType.VARCHAR),
        @Result(column="type_id", property="type_id", jdbcType= JdbcType.INTEGER),
        @Result(column="category_id", property="category_id", jdbcType= JdbcType.INTEGER),
        @Result(column="brand_id", property="brand_id", jdbcType= JdbcType.INTEGER),
        @Result(column="price", property="price", jdbcType= JdbcType.DECIMAL),
        @Result(column="market_price", property="market_price", jdbcType= JdbcType.DECIMAL),
        @Result(column="cost_price", property="cost_price", jdbcType= JdbcType.DECIMAL),
        @Result(column="stock", property="stock", jdbcType= JdbcType.INTEGER),
        @Result(column="warning_stock", property="warning_stock", jdbcType= JdbcType.INTEGER),
        @Result(column="integral", property="integral", jdbcType= JdbcType.INTEGER),
        @Result(column="picture_url", property="picture_url", jdbcType= JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType= JdbcType.VARCHAR),
        @Result(column="create_time", property="create_time", jdbcType= JdbcType.TIMESTAMP),
        @Result(column="index_type", property="index_type", jdbcType= JdbcType.INTEGER)
    })
    Product selectByPrimaryKey(Integer product_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    @UpdateProvider(type=ProductSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    @UpdateProvider(type=ProductSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    @UpdateProvider(type=ProductSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Sep 30 11:22:13 CST 2017
     */
    @Update({
        "update product",
        "set product_name = #{product_name,jdbcType=VARCHAR},",
          "marque = #{marque,jdbcType=VARCHAR},",
          "barcode = #{barcode,jdbcType=VARCHAR},",
          "type_id = #{type_id,jdbcType=INTEGER},",
          "category_id = #{category_id,jdbcType=INTEGER},",
          "brand_id = #{brand_id,jdbcType=INTEGER},",
          "price = #{price,jdbcType=DECIMAL},",
          "market_price = #{market_price,jdbcType=DECIMAL},",
          "cost_price = #{cost_price,jdbcType=DECIMAL},",
          "stock = #{stock,jdbcType=INTEGER},",
          "warning_stock = #{warning_stock,jdbcType=INTEGER},",
          "integral = #{integral,jdbcType=INTEGER},",
          "picture_url = #{picture_url,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "create_time = #{create_time,jdbcType=TIMESTAMP},",
          "index_type = #{index_type,jdbcType=INTEGER}",
        "where product_id = #{product_id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Product record);
}