package com.imory.shop.dao;

import com.imory.shop.dto.ShopPingCart;
import com.imory.shop.dto.ShopPingCartExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface ShopPingCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    @SelectProvider(type=ShopPingCartSqlProvider.class, method="countByExample")
    int countByExample(ShopPingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    @DeleteProvider(type=ShopPingCartSqlProvider.class, method="deleteByExample")
    int deleteByExample(ShopPingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    @Delete({
        "delete from shoppingcart",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    @Insert({
        "insert into shoppingcart (user_id, shop_id, ",
        "product_id, is_product_exists, ",
        "number, created_time)",
        "values (#{user_id,jdbcType=INTEGER}, #{shop_id,jdbcType=INTEGER}, ",
        "#{product_id,jdbcType=INTEGER}, #{is_product_exists,jdbcType=BIT}, ",
        "#{number,jdbcType=INTEGER}, #{created_time,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ShopPingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    @InsertProvider(type=ShopPingCartSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(ShopPingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    @SelectProvider(type=ShopPingCartSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType= JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="user_id", jdbcType= JdbcType.INTEGER),
        @Result(column="shop_id", property="shop_id", jdbcType= JdbcType.INTEGER),
        @Result(column="product_id", property="product_id", jdbcType= JdbcType.INTEGER),
        @Result(column="is_product_exists", property="is_product_exists", jdbcType= JdbcType.BIT),
        @Result(column="number", property="number", jdbcType= JdbcType.INTEGER),
        @Result(column="created_time", property="created_time", jdbcType= JdbcType.TIMESTAMP)
    })
    List<com.imory.shop.dto.ShopPingCart> selectByExample(ShopPingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    @Select({
        "select",
        "id, user_id, shop_id, product_id, is_product_exists, number, created_time",
        "from shoppingcart",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType= JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="user_id", jdbcType= JdbcType.INTEGER),
        @Result(column="shop_id", property="shop_id", jdbcType= JdbcType.INTEGER),
        @Result(column="product_id", property="product_id", jdbcType= JdbcType.INTEGER),
        @Result(column="is_product_exists", property="is_product_exists", jdbcType= JdbcType.BIT),
        @Result(column="number", property="number", jdbcType= JdbcType.INTEGER),
        @Result(column="created_time", property="created_time", jdbcType= JdbcType.TIMESTAMP)
    })
    ShopPingCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    @UpdateProvider(type=ShopPingCartSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ShopPingCart record, @Param("example") ShopPingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    @UpdateProvider(type=ShopPingCartSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ShopPingCart record, @Param("example") ShopPingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    @UpdateProvider(type=ShopPingCartSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ShopPingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    @Update({
        "update shoppingcart",
        "set user_id = #{user_id,jdbcType=INTEGER},",
          "shop_id = #{shop_id,jdbcType=INTEGER},",
          "product_id = #{product_id,jdbcType=INTEGER},",
          "is_product_exists = #{is_product_exists,jdbcType=BIT},",
          "number = #{number,jdbcType=INTEGER},",
          "created_time = #{created_time,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ShopPingCart record);
}