package com.imory.delivery.dao;

import com.imory.delivery.dto.DeliveryAddress;
import com.imory.delivery.dto.DeliveryAddressExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface DeliveryAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    @SelectProvider(type=DeliveryAddressSqlProvider.class, method="countByExample")
    int countByExample(DeliveryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    @DeleteProvider(type=DeliveryAddressSqlProvider.class, method="deleteByExample")
    int deleteByExample(DeliveryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    @Delete({
        "delete from delivery_address",
        "where address_id = #{address_id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer address_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    @Insert({
        "insert into delivery_address (user_id, realname, ",
        "telphone, telphone2, ",
        "country, province, ",
        "city, area, street, ",
        "zip, is_default_address, ",
        "created_time)",
        "values (#{user_id,jdbcType=INTEGER}, #{realname,jdbcType=VARCHAR}, ",
        "#{telphone,jdbcType=VARCHAR}, #{telphone2,jdbcType=VARCHAR}, ",
        "#{country,jdbcType=VARCHAR}, #{province,jdbcType=VARCHAR}, ",
        "#{city,jdbcType=VARCHAR}, #{area,jdbcType=VARCHAR}, #{street,jdbcType=VARCHAR}, ",
        "#{zip,jdbcType=VARCHAR}, #{is_default_address,jdbcType=BIT}, ",
        "#{created_time,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="address_id", before=false, resultType=Integer.class)
    int insert(DeliveryAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    @InsertProvider(type=DeliveryAddressSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="address_id", before=false, resultType=Integer.class)
    int insertSelective(DeliveryAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    @SelectProvider(type=DeliveryAddressSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="address_id", property="address_id", jdbcType= JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="user_id", jdbcType= JdbcType.INTEGER),
        @Result(column="realname", property="realname", jdbcType= JdbcType.VARCHAR),
        @Result(column="telphone", property="telphone", jdbcType= JdbcType.VARCHAR),
        @Result(column="telphone2", property="telphone2", jdbcType= JdbcType.VARCHAR),
        @Result(column="country", property="country", jdbcType= JdbcType.VARCHAR),
        @Result(column="province", property="province", jdbcType= JdbcType.VARCHAR),
        @Result(column="city", property="city", jdbcType= JdbcType.VARCHAR),
        @Result(column="area", property="area", jdbcType= JdbcType.VARCHAR),
        @Result(column="street", property="street", jdbcType= JdbcType.VARCHAR),
        @Result(column="zip", property="zip", jdbcType= JdbcType.VARCHAR),
        @Result(column="is_default_address", property="is_default_address", jdbcType= JdbcType.BIT),
        @Result(column="created_time", property="created_time", jdbcType= JdbcType.TIMESTAMP)
    })
    List<com.imory.delivery.dto.DeliveryAddress> selectByExample(DeliveryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    @Select({
        "select",
        "address_id, user_id, realname, telphone, telphone2, country, province, city, ",
        "area, street, zip, is_default_address, created_time",
        "from delivery_address",
        "where address_id = #{address_id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="address_id", property="address_id", jdbcType= JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="user_id", jdbcType= JdbcType.INTEGER),
        @Result(column="realname", property="realname", jdbcType= JdbcType.VARCHAR),
        @Result(column="telphone", property="telphone", jdbcType= JdbcType.VARCHAR),
        @Result(column="telphone2", property="telphone2", jdbcType= JdbcType.VARCHAR),
        @Result(column="country", property="country", jdbcType= JdbcType.VARCHAR),
        @Result(column="province", property="province", jdbcType= JdbcType.VARCHAR),
        @Result(column="city", property="city", jdbcType= JdbcType.VARCHAR),
        @Result(column="area", property="area", jdbcType= JdbcType.VARCHAR),
        @Result(column="street", property="street", jdbcType= JdbcType.VARCHAR),
        @Result(column="zip", property="zip", jdbcType= JdbcType.VARCHAR),
        @Result(column="is_default_address", property="is_default_address", jdbcType= JdbcType.BIT),
        @Result(column="created_time", property="created_time", jdbcType= JdbcType.TIMESTAMP)
    })
    DeliveryAddress selectByPrimaryKey(Integer address_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    @UpdateProvider(type=DeliveryAddressSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") DeliveryAddress record, @Param("example") DeliveryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    @UpdateProvider(type=DeliveryAddressSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") DeliveryAddress record, @Param("example") DeliveryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    @UpdateProvider(type=DeliveryAddressSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(DeliveryAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    @Update({
        "update delivery_address",
        "set user_id = #{user_id,jdbcType=INTEGER},",
          "realname = #{realname,jdbcType=VARCHAR},",
          "telphone = #{telphone,jdbcType=VARCHAR},",
          "telphone2 = #{telphone2,jdbcType=VARCHAR},",
          "country = #{country,jdbcType=VARCHAR},",
          "province = #{province,jdbcType=VARCHAR},",
          "city = #{city,jdbcType=VARCHAR},",
          "area = #{area,jdbcType=VARCHAR},",
          "street = #{street,jdbcType=VARCHAR},",
          "zip = #{zip,jdbcType=VARCHAR},",
          "is_default_address = #{is_default_address,jdbcType=BIT},",
          "created_time = #{created_time,jdbcType=TIMESTAMP}",
        "where address_id = #{address_id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(DeliveryAddress record);
}