package com.imory.delivery.dto;

import java.util.Date;

public class DeliveryAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.address_id
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    private Integer address_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.user_id
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.realname
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.telphone
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.telphone2
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    private String telphone2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.country
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.province
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.city
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.area
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.street
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    private String street;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.zip
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    private String zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.is_default_address
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    private Boolean is_default_address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.created_time
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    private Date created_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.address_id
     *
     * @return the value of delivery_address.address_id
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public Integer getAddress_id() {
        return address_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.address_id
     *
     * @param address_id the value for delivery_address.address_id
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public void setAddress_id(Integer address_id) {
        this.address_id = address_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.user_id
     *
     * @return the value of delivery_address.user_id
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.user_id
     *
     * @param user_id the value for delivery_address.user_id
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.realname
     *
     * @return the value of delivery_address.realname
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.realname
     *
     * @param realname the value for delivery_address.realname
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.telphone
     *
     * @return the value of delivery_address.telphone
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.telphone
     *
     * @param telphone the value for delivery_address.telphone
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.telphone2
     *
     * @return the value of delivery_address.telphone2
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public String getTelphone2() {
        return telphone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.telphone2
     *
     * @param telphone2 the value for delivery_address.telphone2
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public void setTelphone2(String telphone2) {
        this.telphone2 = telphone2 == null ? null : telphone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.country
     *
     * @return the value of delivery_address.country
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.country
     *
     * @param country the value for delivery_address.country
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.province
     *
     * @return the value of delivery_address.province
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.province
     *
     * @param province the value for delivery_address.province
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.city
     *
     * @return the value of delivery_address.city
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.city
     *
     * @param city the value for delivery_address.city
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.area
     *
     * @return the value of delivery_address.area
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.area
     *
     * @param area the value for delivery_address.area
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.street
     *
     * @return the value of delivery_address.street
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.street
     *
     * @param street the value for delivery_address.street
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.zip
     *
     * @return the value of delivery_address.zip
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.zip
     *
     * @param zip the value for delivery_address.zip
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.is_default_address
     *
     * @return the value of delivery_address.is_default_address
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public Boolean getIs_default_address() {
        return is_default_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.is_default_address
     *
     * @param is_default_address the value for delivery_address.is_default_address
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public void setIs_default_address(Boolean is_default_address) {
        this.is_default_address = is_default_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.created_time
     *
     * @return the value of delivery_address.created_time
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public Date getCreated_time() {
        return created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.created_time
     *
     * @param created_time the value for delivery_address.created_time
     *
     * @mbggenerated Fri Oct 06 15:18:37 CST 2017
     */
    public void setCreated_time(Date created_time) {
        this.created_time = created_time;
    }
}