package com.imory.product.dto;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private Integer product_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private String product_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.marque
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private String marque;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.barcode
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private String barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type_id
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private Integer type_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category_id
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private Integer category_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.brand_id
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private Integer brand_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.market_price
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private BigDecimal market_price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.cost_price
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private BigDecimal cost_price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stock
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.warning_stock
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private Integer warning_stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.integral
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private Integer integral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.picture_url
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private String picture_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.status
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_time
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.index_type
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private Integer index_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.intro
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public Integer getProduct_id() {
        return product_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param product_id the value for product.product_id
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setProduct_id(Integer product_id) {
        this.product_id = product_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public String getProduct_name() {
        return product_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param product_name the value for product.product_name
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setProduct_name(String product_name) {
        this.product_name = product_name == null ? null : product_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.marque
     *
     * @return the value of product.marque
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public String getMarque() {
        return marque;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.marque
     *
     * @param marque the value for product.marque
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setMarque(String marque) {
        this.marque = marque == null ? null : marque.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.barcode
     *
     * @return the value of product.barcode
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.barcode
     *
     * @param barcode the value for product.barcode
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type_id
     *
     * @return the value of product.type_id
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public Integer getType_id() {
        return type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type_id
     *
     * @param type_id the value for product.type_id
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setType_id(Integer type_id) {
        this.type_id = type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public Integer getCategory_id() {
        return category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param category_id the value for product.category_id
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setCategory_id(Integer category_id) {
        this.category_id = category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.brand_id
     *
     * @return the value of product.brand_id
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public Integer getBrand_id() {
        return brand_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.brand_id
     *
     * @param brand_id the value for product.brand_id
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setBrand_id(Integer brand_id) {
        this.brand_id = brand_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.market_price
     *
     * @return the value of product.market_price
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public BigDecimal getMarket_price() {
        return market_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.market_price
     *
     * @param market_price the value for product.market_price
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setMarket_price(BigDecimal market_price) {
        this.market_price = market_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.cost_price
     *
     * @return the value of product.cost_price
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public BigDecimal getCost_price() {
        return cost_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.cost_price
     *
     * @param cost_price the value for product.cost_price
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setCost_price(BigDecimal cost_price) {
        this.cost_price = cost_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stock
     *
     * @return the value of product.stock
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stock
     *
     * @param stock the value for product.stock
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.warning_stock
     *
     * @return the value of product.warning_stock
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public Integer getWarning_stock() {
        return warning_stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.warning_stock
     *
     * @param warning_stock the value for product.warning_stock
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setWarning_stock(Integer warning_stock) {
        this.warning_stock = warning_stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.integral
     *
     * @return the value of product.integral
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.integral
     *
     * @param integral the value for product.integral
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.picture_url
     *
     * @return the value of product.picture_url
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public String getPicture_url() {
        return picture_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.picture_url
     *
     * @param picture_url the value for product.picture_url
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setPicture_url(String picture_url) {
        this.picture_url = picture_url == null ? null : picture_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.status
     *
     * @return the value of product.status
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.status
     *
     * @param status the value for product.status
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_time
     *
     * @return the value of product.create_time
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_time
     *
     * @param create_time the value for product.create_time
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.index_type
     *
     * @return the value of product.index_type
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public Integer getIndex_type() {
        return index_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.index_type
     *
     * @param index_type the value for product.index_type
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setIndex_type(Integer index_type) {
        this.index_type = index_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.intro
     *
     * @return the value of product.intro
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.intro
     *
     * @param intro the value for product.intro
     *
     * @mbggenerated Sat Sep 30 14:33:46 CST 2017
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }
}