package com.imory.common.dao;

import com.imory.common.dto.PhoneCaptcha;
import com.imory.common.dto.PhoneCaptchaExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface PhoneCaptchaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_captcha
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    @SelectProvider(type=PhoneCaptchaSqlProvider.class, method="countByExample")
    int countByExample(PhoneCaptchaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_captcha
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    @DeleteProvider(type=PhoneCaptchaSqlProvider.class, method="deleteByExample")
    int deleteByExample(PhoneCaptchaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_captcha
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    @Delete({
        "delete from phone_captcha",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_captcha
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    @Insert({
        "insert into phone_captcha (phone, confirmCode, ",
        "createTime, expireTime)",
        "values (#{phone,jdbcType=VARCHAR}, #{confirmCode,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{expireTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(PhoneCaptcha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_captcha
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    @InsertProvider(type=PhoneCaptchaSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(PhoneCaptcha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_captcha
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    @SelectProvider(type=PhoneCaptchaSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType= JdbcType.INTEGER, id=true),
        @Result(column="phone", property="phone", jdbcType= JdbcType.VARCHAR),
        @Result(column="confirmCode", property="confirmCode", jdbcType= JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType= JdbcType.TIMESTAMP),
        @Result(column="expireTime", property="expireTime", jdbcType= JdbcType.TIMESTAMP)
    })
    List<com.imory.common.dto.PhoneCaptcha> selectByExample(PhoneCaptchaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_captcha
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    @Select({
        "select",
        "id, phone, confirmCode, createTime, expireTime",
        "from phone_captcha",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType= JdbcType.INTEGER, id=true),
        @Result(column="phone", property="phone", jdbcType= JdbcType.VARCHAR),
        @Result(column="confirmCode", property="confirmCode", jdbcType= JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType= JdbcType.TIMESTAMP),
        @Result(column="expireTime", property="expireTime", jdbcType= JdbcType.TIMESTAMP)
    })
    PhoneCaptcha selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_captcha
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    @UpdateProvider(type=PhoneCaptchaSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PhoneCaptcha record, @Param("example") PhoneCaptchaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_captcha
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    @UpdateProvider(type=PhoneCaptchaSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PhoneCaptcha record, @Param("example") PhoneCaptchaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_captcha
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    @UpdateProvider(type=PhoneCaptchaSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PhoneCaptcha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_captcha
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    @Update({
        "update phone_captcha",
        "set phone = #{phone,jdbcType=VARCHAR},",
          "confirmCode = #{confirmCode,jdbcType=VARCHAR},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "expireTime = #{expireTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PhoneCaptcha record);
}