package com.imory.order.dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrder_idIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrder_idIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_idEqualTo(Integer value) {
            addCriterion("order_id =", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idGreaterThan(Integer value) {
            addCriterion("order_id >", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idLessThan(Integer value) {
            addCriterion("order_id <", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idIn(List<Integer> values) {
            addCriterion("order_id in", values, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idNotIn(List<Integer> values) {
            addCriterion("order_id not in", values, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_noIsNull() {
            addCriterion("order_no is null");
            return (Criteria) this;
        }

        public Criteria andOrder_noIsNotNull() {
            addCriterion("order_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_noEqualTo(String value) {
            addCriterion("order_no =", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noNotEqualTo(String value) {
            addCriterion("order_no <>", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noGreaterThan(String value) {
            addCriterion("order_no >", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noGreaterThanOrEqualTo(String value) {
            addCriterion("order_no >=", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noLessThan(String value) {
            addCriterion("order_no <", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noLessThanOrEqualTo(String value) {
            addCriterion("order_no <=", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noLike(String value) {
            addCriterion("order_no like", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noNotLike(String value) {
            addCriterion("order_no not like", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noIn(List<String> values) {
            addCriterion("order_no in", values, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noNotIn(List<String> values) {
            addCriterion("order_no not in", values, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noBetween(String value1, String value2) {
            addCriterion("order_no between", value1, value2, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noNotBetween(String value1, String value2) {
            addCriterion("order_no not between", value1, value2, "order_no");
            return (Criteria) this;
        }

        public Criteria andShop_idIsNull() {
            addCriterion("shop_id is null");
            return (Criteria) this;
        }

        public Criteria andShop_idIsNotNull() {
            addCriterion("shop_id is not null");
            return (Criteria) this;
        }

        public Criteria andShop_idEqualTo(Integer value) {
            addCriterion("shop_id =", value, "shop_id");
            return (Criteria) this;
        }

        public Criteria andShop_idNotEqualTo(Integer value) {
            addCriterion("shop_id <>", value, "shop_id");
            return (Criteria) this;
        }

        public Criteria andShop_idGreaterThan(Integer value) {
            addCriterion("shop_id >", value, "shop_id");
            return (Criteria) this;
        }

        public Criteria andShop_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("shop_id >=", value, "shop_id");
            return (Criteria) this;
        }

        public Criteria andShop_idLessThan(Integer value) {
            addCriterion("shop_id <", value, "shop_id");
            return (Criteria) this;
        }

        public Criteria andShop_idLessThanOrEqualTo(Integer value) {
            addCriterion("shop_id <=", value, "shop_id");
            return (Criteria) this;
        }

        public Criteria andShop_idIn(List<Integer> values) {
            addCriterion("shop_id in", values, "shop_id");
            return (Criteria) this;
        }

        public Criteria andShop_idNotIn(List<Integer> values) {
            addCriterion("shop_id not in", values, "shop_id");
            return (Criteria) this;
        }

        public Criteria andShop_idBetween(Integer value1, Integer value2) {
            addCriterion("shop_id between", value1, value2, "shop_id");
            return (Criteria) this;
        }

        public Criteria andShop_idNotBetween(Integer value1, Integer value2) {
            addCriterion("shop_id not between", value1, value2, "shop_id");
            return (Criteria) this;
        }

        public Criteria andOrder_statusIsNull() {
            addCriterion("order_status is null");
            return (Criteria) this;
        }

        public Criteria andOrder_statusIsNotNull() {
            addCriterion("order_status is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_statusEqualTo(Integer value) {
            addCriterion("order_status =", value, "order_status");
            return (Criteria) this;
        }

        public Criteria andOrder_statusNotEqualTo(Integer value) {
            addCriterion("order_status <>", value, "order_status");
            return (Criteria) this;
        }

        public Criteria andOrder_statusGreaterThan(Integer value) {
            addCriterion("order_status >", value, "order_status");
            return (Criteria) this;
        }

        public Criteria andOrder_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_status >=", value, "order_status");
            return (Criteria) this;
        }

        public Criteria andOrder_statusLessThan(Integer value) {
            addCriterion("order_status <", value, "order_status");
            return (Criteria) this;
        }

        public Criteria andOrder_statusLessThanOrEqualTo(Integer value) {
            addCriterion("order_status <=", value, "order_status");
            return (Criteria) this;
        }

        public Criteria andOrder_statusIn(List<Integer> values) {
            addCriterion("order_status in", values, "order_status");
            return (Criteria) this;
        }

        public Criteria andOrder_statusNotIn(List<Integer> values) {
            addCriterion("order_status not in", values, "order_status");
            return (Criteria) this;
        }

        public Criteria andOrder_statusBetween(Integer value1, Integer value2) {
            addCriterion("order_status between", value1, value2, "order_status");
            return (Criteria) this;
        }

        public Criteria andOrder_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("order_status not between", value1, value2, "order_status");
            return (Criteria) this;
        }

        public Criteria andProduct_countIsNull() {
            addCriterion("product_count is null");
            return (Criteria) this;
        }

        public Criteria andProduct_countIsNotNull() {
            addCriterion("product_count is not null");
            return (Criteria) this;
        }

        public Criteria andProduct_countEqualTo(Integer value) {
            addCriterion("product_count =", value, "product_count");
            return (Criteria) this;
        }

        public Criteria andProduct_countNotEqualTo(Integer value) {
            addCriterion("product_count <>", value, "product_count");
            return (Criteria) this;
        }

        public Criteria andProduct_countGreaterThan(Integer value) {
            addCriterion("product_count >", value, "product_count");
            return (Criteria) this;
        }

        public Criteria andProduct_countGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_count >=", value, "product_count");
            return (Criteria) this;
        }

        public Criteria andProduct_countLessThan(Integer value) {
            addCriterion("product_count <", value, "product_count");
            return (Criteria) this;
        }

        public Criteria andProduct_countLessThanOrEqualTo(Integer value) {
            addCriterion("product_count <=", value, "product_count");
            return (Criteria) this;
        }

        public Criteria andProduct_countIn(List<Integer> values) {
            addCriterion("product_count in", values, "product_count");
            return (Criteria) this;
        }

        public Criteria andProduct_countNotIn(List<Integer> values) {
            addCriterion("product_count not in", values, "product_count");
            return (Criteria) this;
        }

        public Criteria andProduct_countBetween(Integer value1, Integer value2) {
            addCriterion("product_count between", value1, value2, "product_count");
            return (Criteria) this;
        }

        public Criteria andProduct_countNotBetween(Integer value1, Integer value2) {
            addCriterion("product_count not between", value1, value2, "product_count");
            return (Criteria) this;
        }

        public Criteria andProduct_amount_totalIsNull() {
            addCriterion("product_amount_total is null");
            return (Criteria) this;
        }

        public Criteria andProduct_amount_totalIsNotNull() {
            addCriterion("product_amount_total is not null");
            return (Criteria) this;
        }

        public Criteria andProduct_amount_totalEqualTo(BigDecimal value) {
            addCriterion("product_amount_total =", value, "product_amount_total");
            return (Criteria) this;
        }

        public Criteria andProduct_amount_totalNotEqualTo(BigDecimal value) {
            addCriterion("product_amount_total <>", value, "product_amount_total");
            return (Criteria) this;
        }

        public Criteria andProduct_amount_totalGreaterThan(BigDecimal value) {
            addCriterion("product_amount_total >", value, "product_amount_total");
            return (Criteria) this;
        }

        public Criteria andProduct_amount_totalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("product_amount_total >=", value, "product_amount_total");
            return (Criteria) this;
        }

        public Criteria andProduct_amount_totalLessThan(BigDecimal value) {
            addCriterion("product_amount_total <", value, "product_amount_total");
            return (Criteria) this;
        }

        public Criteria andProduct_amount_totalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("product_amount_total <=", value, "product_amount_total");
            return (Criteria) this;
        }

        public Criteria andProduct_amount_totalIn(List<BigDecimal> values) {
            addCriterion("product_amount_total in", values, "product_amount_total");
            return (Criteria) this;
        }

        public Criteria andProduct_amount_totalNotIn(List<BigDecimal> values) {
            addCriterion("product_amount_total not in", values, "product_amount_total");
            return (Criteria) this;
        }

        public Criteria andProduct_amount_totalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_amount_total between", value1, value2, "product_amount_total");
            return (Criteria) this;
        }

        public Criteria andProduct_amount_totalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_amount_total not between", value1, value2, "product_amount_total");
            return (Criteria) this;
        }

        public Criteria andOrder_amount_totalIsNull() {
            addCriterion("order_amount_total is null");
            return (Criteria) this;
        }

        public Criteria andOrder_amount_totalIsNotNull() {
            addCriterion("order_amount_total is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_amount_totalEqualTo(BigDecimal value) {
            addCriterion("order_amount_total =", value, "order_amount_total");
            return (Criteria) this;
        }

        public Criteria andOrder_amount_totalNotEqualTo(BigDecimal value) {
            addCriterion("order_amount_total <>", value, "order_amount_total");
            return (Criteria) this;
        }

        public Criteria andOrder_amount_totalGreaterThan(BigDecimal value) {
            addCriterion("order_amount_total >", value, "order_amount_total");
            return (Criteria) this;
        }

        public Criteria andOrder_amount_totalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("order_amount_total >=", value, "order_amount_total");
            return (Criteria) this;
        }

        public Criteria andOrder_amount_totalLessThan(BigDecimal value) {
            addCriterion("order_amount_total <", value, "order_amount_total");
            return (Criteria) this;
        }

        public Criteria andOrder_amount_totalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("order_amount_total <=", value, "order_amount_total");
            return (Criteria) this;
        }

        public Criteria andOrder_amount_totalIn(List<BigDecimal> values) {
            addCriterion("order_amount_total in", values, "order_amount_total");
            return (Criteria) this;
        }

        public Criteria andOrder_amount_totalNotIn(List<BigDecimal> values) {
            addCriterion("order_amount_total not in", values, "order_amount_total");
            return (Criteria) this;
        }

        public Criteria andOrder_amount_totalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_amount_total between", value1, value2, "order_amount_total");
            return (Criteria) this;
        }

        public Criteria andOrder_amount_totalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_amount_total not between", value1, value2, "order_amount_total");
            return (Criteria) this;
        }

        public Criteria andLogistics_feeIsNull() {
            addCriterion("logistics_fee is null");
            return (Criteria) this;
        }

        public Criteria andLogistics_feeIsNotNull() {
            addCriterion("logistics_fee is not null");
            return (Criteria) this;
        }

        public Criteria andLogistics_feeEqualTo(BigDecimal value) {
            addCriterion("logistics_fee =", value, "logistics_fee");
            return (Criteria) this;
        }

        public Criteria andLogistics_feeNotEqualTo(BigDecimal value) {
            addCriterion("logistics_fee <>", value, "logistics_fee");
            return (Criteria) this;
        }

        public Criteria andLogistics_feeGreaterThan(BigDecimal value) {
            addCriterion("logistics_fee >", value, "logistics_fee");
            return (Criteria) this;
        }

        public Criteria andLogistics_feeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("logistics_fee >=", value, "logistics_fee");
            return (Criteria) this;
        }

        public Criteria andLogistics_feeLessThan(BigDecimal value) {
            addCriterion("logistics_fee <", value, "logistics_fee");
            return (Criteria) this;
        }

        public Criteria andLogistics_feeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("logistics_fee <=", value, "logistics_fee");
            return (Criteria) this;
        }

        public Criteria andLogistics_feeIn(List<BigDecimal> values) {
            addCriterion("logistics_fee in", values, "logistics_fee");
            return (Criteria) this;
        }

        public Criteria andLogistics_feeNotIn(List<BigDecimal> values) {
            addCriterion("logistics_fee not in", values, "logistics_fee");
            return (Criteria) this;
        }

        public Criteria andLogistics_feeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("logistics_fee between", value1, value2, "logistics_fee");
            return (Criteria) this;
        }

        public Criteria andLogistics_feeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("logistics_fee not between", value1, value2, "logistics_fee");
            return (Criteria) this;
        }

        public Criteria andOrder_coupon_totalIsNull() {
            addCriterion("order_coupon_total is null");
            return (Criteria) this;
        }

        public Criteria andOrder_coupon_totalIsNotNull() {
            addCriterion("order_coupon_total is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_coupon_totalEqualTo(BigDecimal value) {
            addCriterion("order_coupon_total =", value, "order_coupon_total");
            return (Criteria) this;
        }

        public Criteria andOrder_coupon_totalNotEqualTo(BigDecimal value) {
            addCriterion("order_coupon_total <>", value, "order_coupon_total");
            return (Criteria) this;
        }

        public Criteria andOrder_coupon_totalGreaterThan(BigDecimal value) {
            addCriterion("order_coupon_total >", value, "order_coupon_total");
            return (Criteria) this;
        }

        public Criteria andOrder_coupon_totalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("order_coupon_total >=", value, "order_coupon_total");
            return (Criteria) this;
        }

        public Criteria andOrder_coupon_totalLessThan(BigDecimal value) {
            addCriterion("order_coupon_total <", value, "order_coupon_total");
            return (Criteria) this;
        }

        public Criteria andOrder_coupon_totalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("order_coupon_total <=", value, "order_coupon_total");
            return (Criteria) this;
        }

        public Criteria andOrder_coupon_totalIn(List<BigDecimal> values) {
            addCriterion("order_coupon_total in", values, "order_coupon_total");
            return (Criteria) this;
        }

        public Criteria andOrder_coupon_totalNotIn(List<BigDecimal> values) {
            addCriterion("order_coupon_total not in", values, "order_coupon_total");
            return (Criteria) this;
        }

        public Criteria andOrder_coupon_totalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_coupon_total between", value1, value2, "order_coupon_total");
            return (Criteria) this;
        }

        public Criteria andOrder_coupon_totalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_coupon_total not between", value1, value2, "order_coupon_total");
            return (Criteria) this;
        }

        public Criteria andIs_unpacking_inspectionIsNull() {
            addCriterion("is_unpacking_inspection is null");
            return (Criteria) this;
        }

        public Criteria andIs_unpacking_inspectionIsNotNull() {
            addCriterion("is_unpacking_inspection is not null");
            return (Criteria) this;
        }

        public Criteria andIs_unpacking_inspectionEqualTo(Integer value) {
            addCriterion("is_unpacking_inspection =", value, "is_unpacking_inspection");
            return (Criteria) this;
        }

        public Criteria andIs_unpacking_inspectionNotEqualTo(Integer value) {
            addCriterion("is_unpacking_inspection <>", value, "is_unpacking_inspection");
            return (Criteria) this;
        }

        public Criteria andIs_unpacking_inspectionGreaterThan(Integer value) {
            addCriterion("is_unpacking_inspection >", value, "is_unpacking_inspection");
            return (Criteria) this;
        }

        public Criteria andIs_unpacking_inspectionGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_unpacking_inspection >=", value, "is_unpacking_inspection");
            return (Criteria) this;
        }

        public Criteria andIs_unpacking_inspectionLessThan(Integer value) {
            addCriterion("is_unpacking_inspection <", value, "is_unpacking_inspection");
            return (Criteria) this;
        }

        public Criteria andIs_unpacking_inspectionLessThanOrEqualTo(Integer value) {
            addCriterion("is_unpacking_inspection <=", value, "is_unpacking_inspection");
            return (Criteria) this;
        }

        public Criteria andIs_unpacking_inspectionIn(List<Integer> values) {
            addCriterion("is_unpacking_inspection in", values, "is_unpacking_inspection");
            return (Criteria) this;
        }

        public Criteria andIs_unpacking_inspectionNotIn(List<Integer> values) {
            addCriterion("is_unpacking_inspection not in", values, "is_unpacking_inspection");
            return (Criteria) this;
        }

        public Criteria andIs_unpacking_inspectionBetween(Integer value1, Integer value2) {
            addCriterion("is_unpacking_inspection between", value1, value2, "is_unpacking_inspection");
            return (Criteria) this;
        }

        public Criteria andIs_unpacking_inspectionNotBetween(Integer value1, Integer value2) {
            addCriterion("is_unpacking_inspection not between", value1, value2, "is_unpacking_inspection");
            return (Criteria) this;
        }

        public Criteria andIsinvoiceFlagIsNull() {
            addCriterion("isinvoiceFlag is null");
            return (Criteria) this;
        }

        public Criteria andIsinvoiceFlagIsNotNull() {
            addCriterion("isinvoiceFlag is not null");
            return (Criteria) this;
        }

        public Criteria andIsinvoiceFlagEqualTo(Integer value) {
            addCriterion("isinvoiceFlag =", value, "isinvoiceFlag");
            return (Criteria) this;
        }

        public Criteria andIsinvoiceFlagNotEqualTo(Integer value) {
            addCriterion("isinvoiceFlag <>", value, "isinvoiceFlag");
            return (Criteria) this;
        }

        public Criteria andIsinvoiceFlagGreaterThan(Integer value) {
            addCriterion("isinvoiceFlag >", value, "isinvoiceFlag");
            return (Criteria) this;
        }

        public Criteria andIsinvoiceFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("isinvoiceFlag >=", value, "isinvoiceFlag");
            return (Criteria) this;
        }

        public Criteria andIsinvoiceFlagLessThan(Integer value) {
            addCriterion("isinvoiceFlag <", value, "isinvoiceFlag");
            return (Criteria) this;
        }

        public Criteria andIsinvoiceFlagLessThanOrEqualTo(Integer value) {
            addCriterion("isinvoiceFlag <=", value, "isinvoiceFlag");
            return (Criteria) this;
        }

        public Criteria andIsinvoiceFlagIn(List<Integer> values) {
            addCriterion("isinvoiceFlag in", values, "isinvoiceFlag");
            return (Criteria) this;
        }

        public Criteria andIsinvoiceFlagNotIn(List<Integer> values) {
            addCriterion("isinvoiceFlag not in", values, "isinvoiceFlag");
            return (Criteria) this;
        }

        public Criteria andIsinvoiceFlagBetween(Integer value1, Integer value2) {
            addCriterion("isinvoiceFlag between", value1, value2, "isinvoiceFlag");
            return (Criteria) this;
        }

        public Criteria andIsinvoiceFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("isinvoiceFlag not between", value1, value2, "isinvoiceFlag");
            return (Criteria) this;
        }

        public Criteria andInvoice_idIsNull() {
            addCriterion("invoice_id is null");
            return (Criteria) this;
        }

        public Criteria andInvoice_idIsNotNull() {
            addCriterion("invoice_id is not null");
            return (Criteria) this;
        }

        public Criteria andInvoice_idEqualTo(Integer value) {
            addCriterion("invoice_id =", value, "invoice_id");
            return (Criteria) this;
        }

        public Criteria andInvoice_idNotEqualTo(Integer value) {
            addCriterion("invoice_id <>", value, "invoice_id");
            return (Criteria) this;
        }

        public Criteria andInvoice_idGreaterThan(Integer value) {
            addCriterion("invoice_id >", value, "invoice_id");
            return (Criteria) this;
        }

        public Criteria andInvoice_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("invoice_id >=", value, "invoice_id");
            return (Criteria) this;
        }

        public Criteria andInvoice_idLessThan(Integer value) {
            addCriterion("invoice_id <", value, "invoice_id");
            return (Criteria) this;
        }

        public Criteria andInvoice_idLessThanOrEqualTo(Integer value) {
            addCriterion("invoice_id <=", value, "invoice_id");
            return (Criteria) this;
        }

        public Criteria andInvoice_idIn(List<Integer> values) {
            addCriterion("invoice_id in", values, "invoice_id");
            return (Criteria) this;
        }

        public Criteria andInvoice_idNotIn(List<Integer> values) {
            addCriterion("invoice_id not in", values, "invoice_id");
            return (Criteria) this;
        }

        public Criteria andInvoice_idBetween(Integer value1, Integer value2) {
            addCriterion("invoice_id between", value1, value2, "invoice_id");
            return (Criteria) this;
        }

        public Criteria andInvoice_idNotBetween(Integer value1, Integer value2) {
            addCriterion("invoice_id not between", value1, value2, "invoice_id");
            return (Criteria) this;
        }

        public Criteria andAddress_idIsNull() {
            addCriterion("address_id is null");
            return (Criteria) this;
        }

        public Criteria andAddress_idIsNotNull() {
            addCriterion("address_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddress_idEqualTo(Integer value) {
            addCriterion("address_id =", value, "address_id");
            return (Criteria) this;
        }

        public Criteria andAddress_idNotEqualTo(Integer value) {
            addCriterion("address_id <>", value, "address_id");
            return (Criteria) this;
        }

        public Criteria andAddress_idGreaterThan(Integer value) {
            addCriterion("address_id >", value, "address_id");
            return (Criteria) this;
        }

        public Criteria andAddress_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("address_id >=", value, "address_id");
            return (Criteria) this;
        }

        public Criteria andAddress_idLessThan(Integer value) {
            addCriterion("address_id <", value, "address_id");
            return (Criteria) this;
        }

        public Criteria andAddress_idLessThanOrEqualTo(Integer value) {
            addCriterion("address_id <=", value, "address_id");
            return (Criteria) this;
        }

        public Criteria andAddress_idIn(List<Integer> values) {
            addCriterion("address_id in", values, "address_id");
            return (Criteria) this;
        }

        public Criteria andAddress_idNotIn(List<Integer> values) {
            addCriterion("address_id not in", values, "address_id");
            return (Criteria) this;
        }

        public Criteria andAddress_idBetween(Integer value1, Integer value2) {
            addCriterion("address_id between", value1, value2, "address_id");
            return (Criteria) this;
        }

        public Criteria andAddress_idNotBetween(Integer value1, Integer value2) {
            addCriterion("address_id not between", value1, value2, "address_id");
            return (Criteria) this;
        }

        public Criteria andOrderlogistics_idIsNull() {
            addCriterion("orderlogistics_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderlogistics_idIsNotNull() {
            addCriterion("orderlogistics_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderlogistics_idEqualTo(Integer value) {
            addCriterion("orderlogistics_id =", value, "orderlogistics_id");
            return (Criteria) this;
        }

        public Criteria andOrderlogistics_idNotEqualTo(Integer value) {
            addCriterion("orderlogistics_id <>", value, "orderlogistics_id");
            return (Criteria) this;
        }

        public Criteria andOrderlogistics_idGreaterThan(Integer value) {
            addCriterion("orderlogistics_id >", value, "orderlogistics_id");
            return (Criteria) this;
        }

        public Criteria andOrderlogistics_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderlogistics_id >=", value, "orderlogistics_id");
            return (Criteria) this;
        }

        public Criteria andOrderlogistics_idLessThan(Integer value) {
            addCriterion("orderlogistics_id <", value, "orderlogistics_id");
            return (Criteria) this;
        }

        public Criteria andOrderlogistics_idLessThanOrEqualTo(Integer value) {
            addCriterion("orderlogistics_id <=", value, "orderlogistics_id");
            return (Criteria) this;
        }

        public Criteria andOrderlogistics_idIn(List<Integer> values) {
            addCriterion("orderlogistics_id in", values, "orderlogistics_id");
            return (Criteria) this;
        }

        public Criteria andOrderlogistics_idNotIn(List<Integer> values) {
            addCriterion("orderlogistics_id not in", values, "orderlogistics_id");
            return (Criteria) this;
        }

        public Criteria andOrderlogistics_idBetween(Integer value1, Integer value2) {
            addCriterion("orderlogistics_id between", value1, value2, "orderlogistics_id");
            return (Criteria) this;
        }

        public Criteria andOrderlogistics_idNotBetween(Integer value1, Integer value2) {
            addCriterion("orderlogistics_id not between", value1, value2, "orderlogistics_id");
            return (Criteria) this;
        }

        public Criteria andPay_channelIsNull() {
            addCriterion("pay_channel is null");
            return (Criteria) this;
        }

        public Criteria andPay_channelIsNotNull() {
            addCriterion("pay_channel is not null");
            return (Criteria) this;
        }

        public Criteria andPay_channelEqualTo(String value) {
            addCriterion("pay_channel =", value, "pay_channel");
            return (Criteria) this;
        }

        public Criteria andPay_channelNotEqualTo(String value) {
            addCriterion("pay_channel <>", value, "pay_channel");
            return (Criteria) this;
        }

        public Criteria andPay_channelGreaterThan(String value) {
            addCriterion("pay_channel >", value, "pay_channel");
            return (Criteria) this;
        }

        public Criteria andPay_channelGreaterThanOrEqualTo(String value) {
            addCriterion("pay_channel >=", value, "pay_channel");
            return (Criteria) this;
        }

        public Criteria andPay_channelLessThan(String value) {
            addCriterion("pay_channel <", value, "pay_channel");
            return (Criteria) this;
        }

        public Criteria andPay_channelLessThanOrEqualTo(String value) {
            addCriterion("pay_channel <=", value, "pay_channel");
            return (Criteria) this;
        }

        public Criteria andPay_channelLike(String value) {
            addCriterion("pay_channel like", value, "pay_channel");
            return (Criteria) this;
        }

        public Criteria andPay_channelNotLike(String value) {
            addCriterion("pay_channel not like", value, "pay_channel");
            return (Criteria) this;
        }

        public Criteria andPay_channelIn(List<String> values) {
            addCriterion("pay_channel in", values, "pay_channel");
            return (Criteria) this;
        }

        public Criteria andPay_channelNotIn(List<String> values) {
            addCriterion("pay_channel not in", values, "pay_channel");
            return (Criteria) this;
        }

        public Criteria andPay_channelBetween(String value1, String value2) {
            addCriterion("pay_channel between", value1, value2, "pay_channel");
            return (Criteria) this;
        }

        public Criteria andPay_channelNotBetween(String value1, String value2) {
            addCriterion("pay_channel not between", value1, value2, "pay_channel");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noIsNull() {
            addCriterion("out_trade_no is null");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noIsNotNull() {
            addCriterion("out_trade_no is not null");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noEqualTo(String value) {
            addCriterion("out_trade_no =", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noNotEqualTo(String value) {
            addCriterion("out_trade_no <>", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noGreaterThan(String value) {
            addCriterion("out_trade_no >", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noGreaterThanOrEqualTo(String value) {
            addCriterion("out_trade_no >=", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noLessThan(String value) {
            addCriterion("out_trade_no <", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noLessThanOrEqualTo(String value) {
            addCriterion("out_trade_no <=", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noLike(String value) {
            addCriterion("out_trade_no like", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noNotLike(String value) {
            addCriterion("out_trade_no not like", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noIn(List<String> values) {
            addCriterion("out_trade_no in", values, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noNotIn(List<String> values) {
            addCriterion("out_trade_no not in", values, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noBetween(String value1, String value2) {
            addCriterion("out_trade_no between", value1, value2, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noNotBetween(String value1, String value2) {
            addCriterion("out_trade_no not between", value1, value2, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andEscrow_trade_noIsNull() {
            addCriterion("escrow_trade_no is null");
            return (Criteria) this;
        }

        public Criteria andEscrow_trade_noIsNotNull() {
            addCriterion("escrow_trade_no is not null");
            return (Criteria) this;
        }

        public Criteria andEscrow_trade_noEqualTo(String value) {
            addCriterion("escrow_trade_no =", value, "escrow_trade_no");
            return (Criteria) this;
        }

        public Criteria andEscrow_trade_noNotEqualTo(String value) {
            addCriterion("escrow_trade_no <>", value, "escrow_trade_no");
            return (Criteria) this;
        }

        public Criteria andEscrow_trade_noGreaterThan(String value) {
            addCriterion("escrow_trade_no >", value, "escrow_trade_no");
            return (Criteria) this;
        }

        public Criteria andEscrow_trade_noGreaterThanOrEqualTo(String value) {
            addCriterion("escrow_trade_no >=", value, "escrow_trade_no");
            return (Criteria) this;
        }

        public Criteria andEscrow_trade_noLessThan(String value) {
            addCriterion("escrow_trade_no <", value, "escrow_trade_no");
            return (Criteria) this;
        }

        public Criteria andEscrow_trade_noLessThanOrEqualTo(String value) {
            addCriterion("escrow_trade_no <=", value, "escrow_trade_no");
            return (Criteria) this;
        }

        public Criteria andEscrow_trade_noLike(String value) {
            addCriterion("escrow_trade_no like", value, "escrow_trade_no");
            return (Criteria) this;
        }

        public Criteria andEscrow_trade_noNotLike(String value) {
            addCriterion("escrow_trade_no not like", value, "escrow_trade_no");
            return (Criteria) this;
        }

        public Criteria andEscrow_trade_noIn(List<String> values) {
            addCriterion("escrow_trade_no in", values, "escrow_trade_no");
            return (Criteria) this;
        }

        public Criteria andEscrow_trade_noNotIn(List<String> values) {
            addCriterion("escrow_trade_no not in", values, "escrow_trade_no");
            return (Criteria) this;
        }

        public Criteria andEscrow_trade_noBetween(String value1, String value2) {
            addCriterion("escrow_trade_no between", value1, value2, "escrow_trade_no");
            return (Criteria) this;
        }

        public Criteria andEscrow_trade_noNotBetween(String value1, String value2) {
            addCriterion("escrow_trade_no not between", value1, value2, "escrow_trade_no");
            return (Criteria) this;
        }

        public Criteria andOrderTimeIsNull() {
            addCriterion("orderTime is null");
            return (Criteria) this;
        }

        public Criteria andOrderTimeIsNotNull() {
            addCriterion("orderTime is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTimeEqualTo(Date value) {
            addCriterion("orderTime =", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeNotEqualTo(Date value) {
            addCriterion("orderTime <>", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeGreaterThan(Date value) {
            addCriterion("orderTime >", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("orderTime >=", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeLessThan(Date value) {
            addCriterion("orderTime <", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeLessThanOrEqualTo(Date value) {
            addCriterion("orderTime <=", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeIn(List<Date> values) {
            addCriterion("orderTime in", values, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeNotIn(List<Date> values) {
            addCriterion("orderTime not in", values, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeBetween(Date value1, Date value2) {
            addCriterion("orderTime between", value1, value2, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeNotBetween(Date value1, Date value2) {
            addCriterion("orderTime not between", value1, value2, "orderTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNull() {
            addCriterion("payTime is null");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNotNull() {
            addCriterion("payTime is not null");
            return (Criteria) this;
        }

        public Criteria andPayTimeEqualTo(Date value) {
            addCriterion("payTime =", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotEqualTo(Date value) {
            addCriterion("payTime <>", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThan(Date value) {
            addCriterion("payTime >", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("payTime >=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThan(Date value) {
            addCriterion("payTime <", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThanOrEqualTo(Date value) {
            addCriterion("payTime <=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeIn(List<Date> values) {
            addCriterion("payTime in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotIn(List<Date> values) {
            addCriterion("payTime not in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeBetween(Date value1, Date value2) {
            addCriterion("payTime between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotBetween(Date value1, Date value2) {
            addCriterion("payTime not between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andLogisticsTimeIsNull() {
            addCriterion("logisticsTime is null");
            return (Criteria) this;
        }

        public Criteria andLogisticsTimeIsNotNull() {
            addCriterion("logisticsTime is not null");
            return (Criteria) this;
        }

        public Criteria andLogisticsTimeEqualTo(Date value) {
            addCriterion("logisticsTime =", value, "logisticsTime");
            return (Criteria) this;
        }

        public Criteria andLogisticsTimeNotEqualTo(Date value) {
            addCriterion("logisticsTime <>", value, "logisticsTime");
            return (Criteria) this;
        }

        public Criteria andLogisticsTimeGreaterThan(Date value) {
            addCriterion("logisticsTime >", value, "logisticsTime");
            return (Criteria) this;
        }

        public Criteria andLogisticsTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("logisticsTime >=", value, "logisticsTime");
            return (Criteria) this;
        }

        public Criteria andLogisticsTimeLessThan(Date value) {
            addCriterion("logisticsTime <", value, "logisticsTime");
            return (Criteria) this;
        }

        public Criteria andLogisticsTimeLessThanOrEqualTo(Date value) {
            addCriterion("logisticsTime <=", value, "logisticsTime");
            return (Criteria) this;
        }

        public Criteria andLogisticsTimeIn(List<Date> values) {
            addCriterion("logisticsTime in", values, "logisticsTime");
            return (Criteria) this;
        }

        public Criteria andLogisticsTimeNotIn(List<Date> values) {
            addCriterion("logisticsTime not in", values, "logisticsTime");
            return (Criteria) this;
        }

        public Criteria andLogisticsTimeBetween(Date value1, Date value2) {
            addCriterion("logisticsTime between", value1, value2, "logisticsTime");
            return (Criteria) this;
        }

        public Criteria andLogisticsTimeNotBetween(Date value1, Date value2) {
            addCriterion("logisticsTime not between", value1, value2, "logisticsTime");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(Integer value) {
            addCriterion("user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(Integer value) {
            addCriterion("user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(Integer value) {
            addCriterion("user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<Integer> values) {
            addCriterion("user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_remarkIsNull() {
            addCriterion("user_remark is null");
            return (Criteria) this;
        }

        public Criteria andUser_remarkIsNotNull() {
            addCriterion("user_remark is not null");
            return (Criteria) this;
        }

        public Criteria andUser_remarkEqualTo(String value) {
            addCriterion("user_remark =", value, "user_remark");
            return (Criteria) this;
        }

        public Criteria andUser_remarkNotEqualTo(String value) {
            addCriterion("user_remark <>", value, "user_remark");
            return (Criteria) this;
        }

        public Criteria andUser_remarkGreaterThan(String value) {
            addCriterion("user_remark >", value, "user_remark");
            return (Criteria) this;
        }

        public Criteria andUser_remarkGreaterThanOrEqualTo(String value) {
            addCriterion("user_remark >=", value, "user_remark");
            return (Criteria) this;
        }

        public Criteria andUser_remarkLessThan(String value) {
            addCriterion("user_remark <", value, "user_remark");
            return (Criteria) this;
        }

        public Criteria andUser_remarkLessThanOrEqualTo(String value) {
            addCriterion("user_remark <=", value, "user_remark");
            return (Criteria) this;
        }

        public Criteria andUser_remarkLike(String value) {
            addCriterion("user_remark like", value, "user_remark");
            return (Criteria) this;
        }

        public Criteria andUser_remarkNotLike(String value) {
            addCriterion("user_remark not like", value, "user_remark");
            return (Criteria) this;
        }

        public Criteria andUser_remarkIn(List<String> values) {
            addCriterion("user_remark in", values, "user_remark");
            return (Criteria) this;
        }

        public Criteria andUser_remarkNotIn(List<String> values) {
            addCriterion("user_remark not in", values, "user_remark");
            return (Criteria) this;
        }

        public Criteria andUser_remarkBetween(String value1, String value2) {
            addCriterion("user_remark between", value1, value2, "user_remark");
            return (Criteria) this;
        }

        public Criteria andUser_remarkNotBetween(String value1, String value2) {
            addCriterion("user_remark not between", value1, value2, "user_remark");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_statusIsNull() {
            addCriterion("order_settlement_status is null");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_statusIsNotNull() {
            addCriterion("order_settlement_status is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_statusEqualTo(Integer value) {
            addCriterion("order_settlement_status =", value, "order_settlement_status");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_statusNotEqualTo(Integer value) {
            addCriterion("order_settlement_status <>", value, "order_settlement_status");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_statusGreaterThan(Integer value) {
            addCriterion("order_settlement_status >", value, "order_settlement_status");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_settlement_status >=", value, "order_settlement_status");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_statusLessThan(Integer value) {
            addCriterion("order_settlement_status <", value, "order_settlement_status");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_statusLessThanOrEqualTo(Integer value) {
            addCriterion("order_settlement_status <=", value, "order_settlement_status");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_statusIn(List<Integer> values) {
            addCriterion("order_settlement_status in", values, "order_settlement_status");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_statusNotIn(List<Integer> values) {
            addCriterion("order_settlement_status not in", values, "order_settlement_status");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_statusBetween(Integer value1, Integer value2) {
            addCriterion("order_settlement_status between", value1, value2, "order_settlement_status");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("order_settlement_status not between", value1, value2, "order_settlement_status");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_timeIsNull() {
            addCriterion("order_settlement_time is null");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_timeIsNotNull() {
            addCriterion("order_settlement_time is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_timeEqualTo(Date value) {
            addCriterion("order_settlement_time =", value, "order_settlement_time");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_timeNotEqualTo(Date value) {
            addCriterion("order_settlement_time <>", value, "order_settlement_time");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_timeGreaterThan(Date value) {
            addCriterion("order_settlement_time >", value, "order_settlement_time");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("order_settlement_time >=", value, "order_settlement_time");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_timeLessThan(Date value) {
            addCriterion("order_settlement_time <", value, "order_settlement_time");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_timeLessThanOrEqualTo(Date value) {
            addCriterion("order_settlement_time <=", value, "order_settlement_time");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_timeIn(List<Date> values) {
            addCriterion("order_settlement_time in", values, "order_settlement_time");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_timeNotIn(List<Date> values) {
            addCriterion("order_settlement_time not in", values, "order_settlement_time");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_timeBetween(Date value1, Date value2) {
            addCriterion("order_settlement_time between", value1, value2, "order_settlement_time");
            return (Criteria) this;
        }

        public Criteria andOrder_settlement_timeNotBetween(Date value1, Date value2) {
            addCriterion("order_settlement_time not between", value1, value2, "order_settlement_time");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbggenerated do_not_delete_during_merge Thu Oct 05 16:27:57 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}