package com.imory.shop.dto;

import java.util.Date;

public class ShopPingCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.id
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.user_id
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.shop_id
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    private Integer shop_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.product_id
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    private Integer product_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.is_product_exists
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    private Boolean is_product_exists;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.number
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.created_time
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    private Date created_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.id
     *
     * @return the value of shoppingcart.id
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.id
     *
     * @param id the value for shoppingcart.id
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.user_id
     *
     * @return the value of shoppingcart.user_id
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.user_id
     *
     * @param user_id the value for shoppingcart.user_id
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.shop_id
     *
     * @return the value of shoppingcart.shop_id
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.shop_id
     *
     * @param shop_id the value for shoppingcart.shop_id
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.product_id
     *
     * @return the value of shoppingcart.product_id
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    public Integer getProduct_id() {
        return product_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.product_id
     *
     * @param product_id the value for shoppingcart.product_id
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    public void setProduct_id(Integer product_id) {
        this.product_id = product_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.is_product_exists
     *
     * @return the value of shoppingcart.is_product_exists
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    public Boolean getIs_product_exists() {
        return is_product_exists;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.is_product_exists
     *
     * @param is_product_exists the value for shoppingcart.is_product_exists
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    public void setIs_product_exists(Boolean is_product_exists) {
        this.is_product_exists = is_product_exists;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.number
     *
     * @return the value of shoppingcart.number
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.number
     *
     * @param number the value for shoppingcart.number
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.created_time
     *
     * @return the value of shoppingcart.created_time
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    public Date getCreated_time() {
        return created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.created_time
     *
     * @param created_time the value for shoppingcart.created_time
     *
     * @mbggenerated Thu Oct 05 08:44:33 CST 2017
     */
    public void setCreated_time(Date created_time) {
        this.created_time = created_time;
    }
}