package com.imory.user.dao;

import com.imory.user.dto.UserBase;
import com.imory.user.dto.UserBaseExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface UserBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    @SelectProvider(type=UserBaseSqlProvider.class, method="countByExample")
    int countByExample(UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    @DeleteProvider(type=UserBaseSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    @Delete({
        "delete from user_base",
        "where user_id = #{user_id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    @Insert({
        "insert into user_base (user_name, mobile, ",
        "email, password, ",
        "status, create_time)",
        "values (#{user_name,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER}, #{create_time,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="user_id", before=false, resultType=Integer.class)
    int insert(UserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    @InsertProvider(type=UserBaseSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="user_id", before=false, resultType=Integer.class)
    int insertSelective(UserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    @SelectProvider(type=UserBaseSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="user_id", property="user_id", jdbcType= JdbcType.INTEGER, id=true),
        @Result(column="user_name", property="user_name", jdbcType= JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType= JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType= JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType= JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType= JdbcType.INTEGER),
        @Result(column="create_time", property="create_time", jdbcType= JdbcType.TIMESTAMP)
    })
    List<UserBase> selectByExample(UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    @Select({
        "select",
        "user_id, user_name, mobile, email, password, status, create_time",
        "from user_base",
        "where user_id = #{user_id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="user_id", property="user_id", jdbcType= JdbcType.INTEGER, id=true),
        @Result(column="user_name", property="user_name", jdbcType= JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType= JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType= JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType= JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType= JdbcType.INTEGER),
        @Result(column="create_time", property="create_time", jdbcType= JdbcType.TIMESTAMP)
    })
    UserBase selectByPrimaryKey(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    @UpdateProvider(type=UserBaseSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserBase record, @Param("example") UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    @UpdateProvider(type=UserBaseSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UserBase record, @Param("example") UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    @UpdateProvider(type=UserBaseSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    @Update({
        "update user_base",
        "set user_name = #{user_name,jdbcType=VARCHAR},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{create_time,jdbcType=TIMESTAMP}",
        "where user_id = #{user_id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserBase record);
}