package com.imory.order.dao;

import com.imory.order.dto.Order;
import com.imory.order.dto.OrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    @SelectProvider(type=OrderSqlProvider.class, method="countByExample")
    int countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    @DeleteProvider(type=OrderSqlProvider.class, method="deleteByExample")
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    @Delete({
        "delete from order",
        "where order_id = #{order_id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer order_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    @Insert({
        "insert into order (order_no, shop_id, ",
        "order_status, product_count, ",
        "product_amount_total, order_amount_total, ",
        "logistics_fee, order_coupon_total, ",
        "is_unpacking_inspection, isinvoiceFlag, ",
        "invoice_id, address_id, ",
        "orderlogistics_id, pay_channel, ",
        "out_trade_no, escrow_trade_no, ",
        "orderTime, payTime, ",
        "logisticsTime, user_id, ",
        "user_remark, order_settlement_status, ",
        "order_settlement_time, createTime)",
        "values (#{order_no,jdbcType=VARCHAR}, #{shop_id,jdbcType=INTEGER}, ",
        "#{order_status,jdbcType=INTEGER}, #{product_count,jdbcType=INTEGER}, ",
        "#{product_amount_total,jdbcType=DECIMAL}, #{order_amount_total,jdbcType=DECIMAL}, ",
        "#{logistics_fee,jdbcType=DECIMAL}, #{order_coupon_total,jdbcType=DECIMAL}, ",
        "#{is_unpacking_inspection,jdbcType=INTEGER}, #{isinvoiceFlag,jdbcType=INTEGER}, ",
        "#{invoice_id,jdbcType=INTEGER}, #{address_id,jdbcType=INTEGER}, ",
        "#{orderlogistics_id,jdbcType=INTEGER}, #{pay_channel,jdbcType=VARCHAR}, ",
        "#{out_trade_no,jdbcType=VARCHAR}, #{escrow_trade_no,jdbcType=VARCHAR}, ",
        "#{orderTime,jdbcType=TIMESTAMP}, #{payTime,jdbcType=TIMESTAMP}, ",
        "#{logisticsTime,jdbcType=TIMESTAMP}, #{user_id,jdbcType=INTEGER}, ",
        "#{user_remark,jdbcType=VARCHAR}, #{order_settlement_status,jdbcType=INTEGER}, ",
        "#{order_settlement_time,jdbcType=TIMESTAMP}, #{createTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="order_id", before=false, resultType=Integer.class)
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    @InsertProvider(type=OrderSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="order_id", before=false, resultType=Integer.class)
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    @SelectProvider(type=OrderSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="order_id", property="order_id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="order_no", property="order_no", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_id", property="shop_id", jdbcType=JdbcType.INTEGER),
        @Result(column="order_status", property="order_status", jdbcType=JdbcType.INTEGER),
        @Result(column="product_count", property="product_count", jdbcType=JdbcType.INTEGER),
        @Result(column="product_amount_total", property="product_amount_total", jdbcType=JdbcType.DECIMAL),
        @Result(column="order_amount_total", property="order_amount_total", jdbcType=JdbcType.DECIMAL),
        @Result(column="logistics_fee", property="logistics_fee", jdbcType=JdbcType.DECIMAL),
        @Result(column="order_coupon_total", property="order_coupon_total", jdbcType=JdbcType.DECIMAL),
        @Result(column="is_unpacking_inspection", property="is_unpacking_inspection", jdbcType=JdbcType.INTEGER),
        @Result(column="isinvoiceFlag", property="isinvoiceFlag", jdbcType=JdbcType.INTEGER),
        @Result(column="invoice_id", property="invoice_id", jdbcType=JdbcType.INTEGER),
        @Result(column="address_id", property="address_id", jdbcType=JdbcType.INTEGER),
        @Result(column="orderlogistics_id", property="orderlogistics_id", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_channel", property="pay_channel", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_trade_no", property="out_trade_no", jdbcType=JdbcType.VARCHAR),
        @Result(column="escrow_trade_no", property="escrow_trade_no", jdbcType=JdbcType.VARCHAR),
        @Result(column="orderTime", property="orderTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="payTime", property="payTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="logisticsTime", property="logisticsTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user_id", property="user_id", jdbcType=JdbcType.INTEGER),
        @Result(column="user_remark", property="user_remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_settlement_status", property="order_settlement_status", jdbcType=JdbcType.INTEGER),
        @Result(column="order_settlement_time", property="order_settlement_time", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<com.imory.order.dto.Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    @Select({
        "select",
        "order_id, order_no, shop_id, order_status, product_count, product_amount_total, ",
        "order_amount_total, logistics_fee, order_coupon_total, is_unpacking_inspection, ",
        "isinvoiceFlag, invoice_id, address_id, orderlogistics_id, pay_channel, out_trade_no, ",
        "escrow_trade_no, orderTime, payTime, logisticsTime, user_id, user_remark, order_settlement_status, ",
        "order_settlement_time, createTime",
        "from order",
        "where order_id = #{order_id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="order_id", property="order_id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="order_no", property="order_no", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_id", property="shop_id", jdbcType=JdbcType.INTEGER),
        @Result(column="order_status", property="order_status", jdbcType=JdbcType.INTEGER),
        @Result(column="product_count", property="product_count", jdbcType=JdbcType.INTEGER),
        @Result(column="product_amount_total", property="product_amount_total", jdbcType=JdbcType.DECIMAL),
        @Result(column="order_amount_total", property="order_amount_total", jdbcType=JdbcType.DECIMAL),
        @Result(column="logistics_fee", property="logistics_fee", jdbcType=JdbcType.DECIMAL),
        @Result(column="order_coupon_total", property="order_coupon_total", jdbcType=JdbcType.DECIMAL),
        @Result(column="is_unpacking_inspection", property="is_unpacking_inspection", jdbcType=JdbcType.INTEGER),
        @Result(column="isinvoiceFlag", property="isinvoiceFlag", jdbcType=JdbcType.INTEGER),
        @Result(column="invoice_id", property="invoice_id", jdbcType=JdbcType.INTEGER),
        @Result(column="address_id", property="address_id", jdbcType=JdbcType.INTEGER),
        @Result(column="orderlogistics_id", property="orderlogistics_id", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_channel", property="pay_channel", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_trade_no", property="out_trade_no", jdbcType=JdbcType.VARCHAR),
        @Result(column="escrow_trade_no", property="escrow_trade_no", jdbcType=JdbcType.VARCHAR),
        @Result(column="orderTime", property="orderTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="payTime", property="payTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="logisticsTime", property="logisticsTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user_id", property="user_id", jdbcType=JdbcType.INTEGER),
        @Result(column="user_remark", property="user_remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_settlement_status", property="order_settlement_status", jdbcType=JdbcType.INTEGER),
        @Result(column="order_settlement_time", property="order_settlement_time", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    Order selectByPrimaryKey(Integer order_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    @UpdateProvider(type=OrderSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    @UpdateProvider(type=OrderSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    @UpdateProvider(type=OrderSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Oct 05 16:27:57 CST 2017
     */
    @Update({
        "update order",
        "set order_no = #{order_no,jdbcType=VARCHAR},",
          "shop_id = #{shop_id,jdbcType=INTEGER},",
          "order_status = #{order_status,jdbcType=INTEGER},",
          "product_count = #{product_count,jdbcType=INTEGER},",
          "product_amount_total = #{product_amount_total,jdbcType=DECIMAL},",
          "order_amount_total = #{order_amount_total,jdbcType=DECIMAL},",
          "logistics_fee = #{logistics_fee,jdbcType=DECIMAL},",
          "order_coupon_total = #{order_coupon_total,jdbcType=DECIMAL},",
          "is_unpacking_inspection = #{is_unpacking_inspection,jdbcType=INTEGER},",
          "isinvoiceFlag = #{isinvoiceFlag,jdbcType=INTEGER},",
          "invoice_id = #{invoice_id,jdbcType=INTEGER},",
          "address_id = #{address_id,jdbcType=INTEGER},",
          "orderlogistics_id = #{orderlogistics_id,jdbcType=INTEGER},",
          "pay_channel = #{pay_channel,jdbcType=VARCHAR},",
          "out_trade_no = #{out_trade_no,jdbcType=VARCHAR},",
          "escrow_trade_no = #{escrow_trade_no,jdbcType=VARCHAR},",
          "orderTime = #{orderTime,jdbcType=TIMESTAMP},",
          "payTime = #{payTime,jdbcType=TIMESTAMP},",
          "logisticsTime = #{logisticsTime,jdbcType=TIMESTAMP},",
          "user_id = #{user_id,jdbcType=INTEGER},",
          "user_remark = #{user_remark,jdbcType=VARCHAR},",
          "order_settlement_status = #{order_settlement_status,jdbcType=INTEGER},",
          "order_settlement_time = #{order_settlement_time,jdbcType=TIMESTAMP},",
          "createTime = #{createTime,jdbcType=TIMESTAMP}",
        "where order_id = #{order_id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Order record);
}